# Generated by Django 4.2.4 on 2023-10-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('time', models.IntegerField()),
                ('started_date', models.DateTimeField()),
            ],
        ),
    ]
