# Generated by Django 4.2.4 on 2023-10-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cls',
            name='time',
            field=models.TextField(max_length=10),
        ),
    ]
