# Generated by Django 4.2.4 on 2023-10-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_alter_cls_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cls',
            name='started_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cls',
            name='time',
            field=models.CharField(max_length=45),
        ),
    ]
